name: 'Post to Bluesky'

on:
  schedule:
    - cron: '*/10 * * * *'
    - cron: '20 1,14,18,22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Bun runtime
        uses: oven-sh/setup-bun@v2
      - run: bun i --production
      - run: bun run build
      - name: Send post
        run: bun start
        env:
          BSKY_HANDLE: ${{ secrets.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          NODE_ENV: production
